# Generated by Django 5.1.2 on 2024-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default=' ', max_length=250),
        ),
    ]
